name: Render and Deploy RMarkdown Website
on:
  push:
  schedule:
    - cron: '0 0 * * * ' #http://www.cronmaker.com/?0
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: [4.1.2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}		
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}
      - name: Lint
        run: lintr::lint_dir()
        shell: Rscript {0}
      - name: Render Site
        run: |-
          Rscript -e 'rmarkdown::render("proy_proc_sel.Rmd")'