name: Render and Deploy RMarkdown Website
'on': push
  schedule:
    - cron: '35 1 * * THU' # 1.35 am UTC is 11.30 melbourne time
jobs:
  build:
    runs-on: windows-latest
    env:
        BUILD_DIR: $DEPLOY_PATH
        GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}
      - name: Lint
        run: lintr::lint_dir()
        shell: Rscript {0}

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('pacman', 'rsconnect', 'remotes'), type = 'binary', dependencies = TRUE)"
          Rscript -e "remotes::install_deps(type = 'binary', force = FALSE, dependencies = TRUE)"
      - name: Render Site
        run: |-
          Rscript -e "rmarkdown::render("proy_proc_sel.Rmd",encoding = 'UTF-8')"
          echo "::set-env name=DEPLOY_PATH::$(Rscript -e "cat(rmarkdown::site_config()[['output_dir']])")"
      - name: Commit
        run: |
          git config --global user.name 'AGSCL'
          git config --global user.email 'AGSCL@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"